### PR TITLE
Monocraft: Add version 2.1

### PR DESCRIPTION
**Pull request by Zliced13**
A Minecraft based typeface for developers that love Minecraft a bit too much.

### CODE REVIEW

**Comment by Zliced13** [comment]
Hello @matthewjberger, I hope you're having a good day today.

If you don't mind, could you please test my manifests to see if it properly installs the font on your system. I just want to make sure the manifests work for everyone else's systems, not just my system.

**Comment by matthewjberger** [comment]
Looks great. :) Thank you very much for contributing!

image

image

**Comment by matthewjberger** [comment]
This is a pretty cool font, much appreciated 🚀

image

**Comment by Zliced13** [comment]
It's a cool font, I like it myself aswell.

**Pull request merged**
