### PR TITLE
Add Cascadia Code

### LINKED ISSUE #18: Missing cascadia-code
Available here https://github.com/microsoft/cascadia-code

### PR DESCRIPTION
**Pull request by johannesegger**
fixes #18

### CODE REVIEW

**Comment by linyinfeng** [comment]
Hash is missing in the manifest.

**Comment by johannesegger** [comment]
Because the hash should come from the server, shouldn't it? It doesn't feel right to take the hash from the file I just downloaded as the right hash, because that defeats the whole purpose of a hash, doesn't it?

**Comment by matthewjberger** [comment]
For scoop manifests, a hash is included so that there is a reference hash. When scoop downloads a file it will check the hash of the downloaded file against the one in the manifest. If they match you got the intended file. The rest of the manifest looks good to me, so once the hash is added I'll merge the PR. And thank you for your contribution!

**Comment by johannesegger** [comment]
Ok, thanks for clarification. I added the suggested hash.

**Pull request merged**
