### PR TITLE
Add `Ash258/Scoop-GithubActions` to do automated tasks

### LINKED ISSUE #135: Add Scoop-GithubActions ?
I think maybe we can add [Scoop-GithubActions](https://github.com/Ash258/Scoop-GithubActions) for automated validation and more.

### PR DESCRIPTION
**Pull request by jonz94**
Close #135

- Tweak `.editorconfig`, because `.yml` file are usually using 2 space as indentation.
- Currently, I do not set `GITH_MAIL` environment variable because I think commits made by CI does not count as contributions by anyone. But it is just my opinion 😊 and can be changed if needed.

Some information about `GITH_EMAIL` environment variable is not set, quote from [Ash258/Scoop-GithubActions's README](https://github.com/Ash258/Scoop-GithubActions/blob/stable-win/README.md#available-environment-variables)
>`GITH_EMAIL` environment variable is not required since [1.0.1](https://github.com/Ash258/Scoop-GithubActions/releases/tag/1.0.1), but it is recommended.
If email is not specified, commits will not be pushed using account bounded to the email. This will lead to not adding contributions. ([See as example commit from github action without user's email](https://github.com/phips28/gh-action-bump-version/commit/adda5b22b3c785eb69d328f91dadb49a4c34a82e))

### CODE REVIEW

**Comment by jonz94** [comment]
I also create [a demo repository](https://github.com/jonz94/scoop-nerd-fonts-github-actions) as a playground of this PR.
And I think it works really well!

**Comment by Goooler** [comment]
@jonz94 Can you make it run when pushing ?

**Comment by jonz94** [comment]
@Goooler Unfortunately, it seems like `Ash258/Scoop-GithubActions` currently does not support push action yet. The only information I found is that there is a plan to support it in the future (https://github.com/Ash258/Scoop-GithubActions/issues/61).

**Comment by Goooler** [comment]
I'm curious about how it works ?

image

**Comment by rashil2000** [comment]
The check you see in this screenshot is run using AppVeyor, see the file here - https://github.com/ScoopInstaller/Extras/blob/master/appveyor.yml

**Pull request merged**
